#pragma once

static const char HTML_PAGE[] =
    "<!DOCTYPE html>"
    "<html lang='en'>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>Electronic Load</title>"
    "<script src='https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js'></script>"
    "<style>"
    "*{margin:0;padding:0;box-sizing:border-box}"
    "body{background:#1a1a2e;color:#eee;font-family:monospace}"
    ".header{background:#16213e;padding:12px 20px;display:flex;align-items:center;justify-content:space-between}"
    ".header h1{font-size:18px;color:#0f9}"
    ".status{font-size:12px;color:#888}"
    ".status.on{color:#0f9}"
    ".cards{display:flex;gap:12px;padding:16px;flex-wrap:wrap}"
    ".card{background:#16213e;border-radius:8px;padding:16px;flex:1;min-width:140px;text-align:center}"
    ".card .label{font-size:11px;color:#888;margin-bottom:6px}"
    ".card .value{font-size:28px;font-weight:bold;color:#0f9}"
    ".card .unit{font-size:13px;color:#666;margin-left:4px}"
    ".card.warn .value{color:#f90}"
    ".chart-row{display:flex;gap:12px;padding:0 16px 16px;flex-wrap:wrap}"
    ".chart-box{background:#16213e;border-radius:8px;flex:1;min-width:300px}"
    ".chart-box h3{padding:12px 16px 0;font-size:13px;color:#888}"
    "#chart-wave,#chart-iv{height:220px}"
    ".btn{padding:10px 22px;border:none;border-radius:6px;cursor:pointer;font-size:14px;font-weight:bold;transition:.2s}"
    ".btn-on{background:#0f9;color:#000}"
    ".btn-off{background:#f44;color:#fff}"
    ".btn-mode{background:#16213e;color:#0f9;border:1px solid #0f9}"
    ".btn-mode.active{background:#0f9;color:#000}"
    ".btn-bat{background:#16213e;color:#a0f;border:1px solid #a0f}"
    ".btn-bat:disabled{opacity:.5;cursor:not-allowed}"
    ".mode-bar{padding:0 16px 8px;display:flex;gap:8px;flex-wrap:wrap;align-items:center}"
    ".set-bar{padding:0 16px 12px;display:flex;gap:8px;align-items:center;min-height:44px}"
    ".set-bar input{background:#0d1b2a;color:#0f9;border:1px solid #0f9;border-radius:6px;padding:8px 12px;font-size:16px;font-family:monospace;width:120px;outline:none}"
    ".set-bar .unit-label{color:#888;font-size:13px}"
    ".set-bar .btn-set{background:#0f9;color:#000;padding:8px 18px;border:none;border-radius:6px;cursor:pointer;font-size:14px;font-weight:bold}"
    ".set-bar .setval{color:#888;font-size:12px;margin-left:8px}"
    ".bat-section{padding:0 16px 16px;display:none}"
    ".bat-section h2{font-size:13px;color:#888;margin-bottom:8px;border-top:1px solid #222;padding-top:12px}"
    ".bat-bar{width:100%;background:#0d1b2a;border-radius:4px;height:8px;margin-top:6px;overflow:hidden}"
    ".bat-bar-fill{height:100%;border-radius:4px;transition:width .6s}"
    "</style>"
    "</head>"
    "<body>"
    "<div class='header'>"
    "  <h1>智能电源特性分析仪</h1>"
    "  <span class='status' id='ws-status'>Disconnected</span>"
    "</div>"
    "<div class='cards'>"
    "  <div class='card'><div class='label'>电压</div><div><span class='value' id='v'>0.00</span><span class='unit'>V</span></div></div>"
    "  <div class='card'><div class='label'>电流</div><div><span class='value' id='i'>0.00</span><span class='unit'>A</span></div></div>"
    "  <div class='card'><div class='label'>功率</div><div><span class='value' id='p'>0.00</span><span class='unit'>W</span></div></div>"
    "  <div class='card'><div class='label'>模式</div><div><span class='value' id='m' style='font-size:20px'>--</span></div></div>"
    "</div>"
    "<div class='mode-bar'>"
    "  <button type='button' class='btn btn-mode' id='btn-CC' onclick='selectMode(\"CC\")'>CC</button>"
    "  <button type='button' class='btn btn-mode' id='btn-CV' onclick='selectMode(\"CV\")'>CV</button>"
    "  <button type='button' class='btn btn-mode' id='btn-CR' onclick='selectMode(\"CR\")'>CR</button>"
    "  <button type='button' class='btn btn-mode' id='btn-CW' onclick='selectMode(\"CW\")'>CW</button>"
    "  <button type='button' class='btn btn-on' onclick='sendCmd(\"out\",\"1\")'>ON</button>"
    "  <button type='button' class='btn btn-off' onclick='sendCmd(\"out\",\"0\")'>OFF</button>"
    "  <button type='button' class='btn btn-bat' id='btn-bat' onclick='startBatTest()'>BAT</button>"
    "</div>"
    "<div class='set-bar' id='set-bar'>"
    "  <input type='number' id='set-input' placeholder='0.00' step='0.01' min='0'>"
    "  <span class='unit-label' id='set-unit'>A</span>"
    "  <button type='button' class='btn-set' onclick='applySet()'>Set</button>"
    "  <span class='setval' id='set-display'></span>"
    "</div>"
    "<div class='chart-row'>"
    "  <div class='chart-box'><h3>Real-time Waveform</h3><div id='chart-wave'></div></div>"
    "  <div class='chart-box'><h3>IV Curve</h3><div id='chart-iv'></div></div>"
    "</div>"
    "<div class='bat-section' id='bat-section'>"
    "  <h2>Battery Health Test Results</h2>"
    "  <div class='cards'>"
    "    <div class='card'><div class='label'>OCV</div><div><span class='value' id='bat-ocv'>--</span><span class='unit'>V</span></div></div>"
    "    <div class='card'><div class='label'>V @ 0.5A</div><div><span class='value' id='bat-v1'>--</span><span class='unit'>V</span></div></div>"
    "    <div class='card'><div class='label'>V @ 2.0A</div><div><span class='value' id='bat-v2'>--</span><span class='unit'>V</span></div></div>"
    "    <div class='card'><div class='label'>内阻 Ri</div><div><span class='value' id='bat-ri'>--</span><span class='unit'>mΩ</span></div></div>"
    "    <div class='card'><div class='label'>SOH</div><div><span class='value' id='bat-soh'>--</span><span class='unit'>%</span></div>"
    "      <div class='bat-bar'><div class='bat-bar-fill' id='bat-bar-fill' style='width:0%'></div></div>"
    "    </div>"
    "    <div class='card'><div class='label'>健康状态</div><div><span class='value' id='bat-health' style='font-size:20px'>--</span></div></div>"
    "  </div>"
    "</div>"
    "<script>"
    "const MAX_POINTS = 100;"
    "let ws, voltData=[], currData=[], timeData=[];"
    "let curMode='';"
    "const modeUnit={CC:'A',CV:'V',CR:'Ohm',CW:'W'};"
    "const modeMax={CC:10,CV:30,CR:999,CW:200};"

    "const waveChart = echarts.init(document.getElementById('chart-wave'),null,{renderer:'canvas'});"
    "waveChart.setOption({"
    "  backgroundColor:'transparent',"
    "  grid:{top:30,bottom:30,left:50,right:20},"
    "  legend:{data:['V','I'],textStyle:{color:'#888'},top:5},"
    "  xAxis:{type:'category',data:[],axisLabel:{color:'#555'},axisLine:{lineStyle:{color:'#333'}}},"
    "  yAxis:[{type:'value',name:'V',nameTextStyle:{color:'#0f9'},axisLabel:{color:'#0f9'},splitLine:{lineStyle:{color:'#222'}}},"
    "         {type:'value',name:'A',nameTextStyle:{color:'#f90'},axisLabel:{color:'#f90'},splitLine:{show:false}}],"
    "  series:["
    "    {name:'V',type:'line',data:[],yAxisIndex:0,smooth:true,symbol:'none',lineStyle:{color:'#0f9',width:2},areaStyle:{color:'rgba(0,255,153,0.05)'}},"
    "    {name:'I',type:'line',data:[],yAxisIndex:1,smooth:true,symbol:'none',lineStyle:{color:'#f90',width:2}}"
    "  ]"
    "});"

    "const ivChart = echarts.init(document.getElementById('chart-iv'),null,{renderer:'canvas'});"
    "ivChart.setOption({"
    "  backgroundColor:'transparent',"
    "  grid:{top:30,bottom:40,left:50,right:20},"
    "  xAxis:{type:'value',name:'V(V)',nameTextStyle:{color:'#888'},axisLabel:{color:'#888'},splitLine:{lineStyle:{color:'#222'}},min:'dataMin',max:'dataMax'},"
    "  yAxis:{type:'value',name:'I(A)',nameTextStyle:{color:'#888'},axisLabel:{color:'#888'},splitLine:{lineStyle:{color:'#222'}},min:0},"
    "  series:[{name:'IV',type:'line',data:[],smooth:false,symbol:'none',lineStyle:{color:'#f0f',width:2}}]"
    "});"

    "function selectMode(m){"
    "  curMode=m;"
    "  ['CC','CV','CR','CW'].forEach(x=>{"
    "    document.getElementById('btn-'+x).className='btn btn-mode'+(x===m?' active':'');"
    "  });"
    "  document.getElementById('set-unit').textContent=modeUnit[m]||'';"
    "  document.getElementById('set-input').value='';"
    "  document.getElementById('set-input').placeholder='0.00';"
    "  document.getElementById('set-input').max=modeMax[m]||999;"
    "  sendCmd('mode',m);"
    "}"

    "function applySet(){"
    "  if(!curMode){alert('Please select a mode first.');return;}"
    "  const v=parseFloat(document.getElementById('set-input').value);"
    "  if(isNaN(v)||v<0){alert('Invalid value.');return;}"
    "  const intVal=Math.round(v*100);"
    "  if(ws&&ws.readyState===1){"
    "    ws.send(JSON.stringify({type:'set',mode:curMode,val:intVal}));"
    "    document.getElementById('set-display').textContent='Set: '+v.toFixed(2)+' '+modeUnit[curMode];"
    "  } else {"
    "    console.warn('WS not ready');"
    "  }"
    "}"

    "function connectWS(){"
    "  ws = new WebSocket('ws://'+location.hostname+'/ws');"
    "  ws.onopen=()=>{"
    "    document.getElementById('ws-status').textContent='Connected';"
    "    document.getElementById('ws-status').className='status on';"
    "  };"
    "  ws.onclose=()=>{"
    "    document.getElementById('ws-status').textContent='Disconnected';"
    "    document.getElementById('ws-status').className='status';"
    "    setTimeout(connectWS,2000);"
    "  };"
    "  ws.onmessage=e=>{"
    "    try{"
    "      const d=JSON.parse(e.data);"
    "      if(d.v!==undefined){"
    "        const v=(d.v/100).toFixed(2),i=(d.i/100).toFixed(2),p=(d.p/100).toFixed(2);"
    "        document.getElementById('v').textContent=v;"
    "        document.getElementById('i').textContent=i;"
    "        document.getElementById('p').textContent=p;"
    "        const modes=['CC','CV','CR','CW','--'];"
    "        document.getElementById('m').textContent=modes[d.m]||'--';"
    "        const t=new Date().toLocaleTimeString();"
    "        voltData.push(parseFloat(v));currData.push(parseFloat(i));timeData.push(t);"
    "        if(voltData.length>MAX_POINTS){voltData.shift();currData.shift();timeData.shift();}"
    "        waveChart.setOption({xAxis:{data:timeData},series:[{data:voltData},{data:currData}]});"
    "      } else if(d.type==='iv'){"
    "        const pts=d.points.map(pt=>[pt[1]/100, pt[0]/1000]);"
    "        ivChart.setOption({series:[{data:pts}]});"
    "      } else if(d.type==='bat'){"
    "        document.getElementById('bat-section').style.display='block';"
    "        document.getElementById('bat-ocv').textContent=(d.ocv/100).toFixed(2);"
    "        document.getElementById('bat-v1').textContent=(d.v1/100).toFixed(2);"
    "        document.getElementById('bat-v2').textContent=(d.v2/100).toFixed(2);"
    "        document.getElementById('bat-ri').textContent=d.ri;"
    "        document.getElementById('bat-soh').textContent=d.soh;"
    "        const fill=document.getElementById('bat-bar-fill');"
    "        fill.style.width=d.soh+'%';"
    "        fill.style.background=d.soh>=80?'#0f9':d.soh>=60?'#ff0':d.soh>=40?'#f90':'#f44';"
    "        const h=document.getElementById('bat-health');"
    "        h.textContent=d.health;"
    "        h.style.color=d.soh>=80?'#0f9':d.soh>=60?'#ff0':d.soh>=40?'#f90':'#f44';"
    "        const btn=document.getElementById('btn-bat');"
    "        btn.disabled=false;btn.textContent='BAT';"
    "      }"
    "    }catch(err){}"
    "  };"
    "}"

    "function sendCmd(type,val){"
    "  if(ws&&ws.readyState===1){"
    "    ws.send(JSON.stringify({type:type,val:val}));"
    "  } else {"
    "    console.warn('WS not ready, state=',ws?ws.readyState:'null');"
    "  }"
    "}"
    ""
    "function startBatTest(){"
    "  if(!ws||ws.readyState!==1){console.warn('WS not ready');return;}"
    "  const btn=document.getElementById('btn-bat');"
    "  btn.disabled=true;"
    "  btn.textContent='Testing...';"
    "  ws.send(JSON.stringify({type:'bat'}));"
    "}"

    "connectWS();"
    "window.addEventListener('resize',()=>{waveChart.resize();ivChart.resize();});"
    "</script>"
    "</body>"
    "</html>";
